name: heal_happy
description: Heal happy mobile app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.2+22

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_picker: ^4.2.8
  country_code_picker: ^2.0.2
  collection: ^1.15.0
  syncfusion_flutter_barcodes: ^19.4.54
  syncfusion_flutter_charts: ^19.3.59
  url_launcher: ^6.0.17
  dio:
  syncfusion_flutter_calendar: ^19.4.50
  built_value:
  intl: ^0.17.0
  pubspec_parse: ^1.2.0
  stream_transform: ^2.0.0
  shared_preferences: ^2.0.11
  go_router: ^3.0.2
  heal_happy_sdk:
    path: '../api'
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.1
  sentry_flutter: ^6.3.0
  logging: ^1.0.2
  jitsi_meet_wrapper: ^0.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/files/
     - pubspec.yaml
