name: heal_happy
description: Heal happy mobile app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.1+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stripe_checkout: ^1.0.0
  file_picker: ^4.6.1
  country_code_picker: ^2.0.2
  collection: ^1.15.0
  syncfusion_flutter_barcodes: ^20.1.59
  syncfusion_flutter_charts: ^20.1.59
  syncfusion_flutter_calendar: ^20.1.59
  url_launcher: ^6.1.3
  dio:
  built_value:
  intl: ^0.17.0
  pubspec_parse: ^1.2.0
  stream_transform: ^2.0.0
  shared_preferences: ^2.0.15
  go_router: ^3.1.1
  heal_happy_sdk:
    path: '../api'
  flutter_riverpod: ^1.0.4
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.4
  sentry_flutter: ^6.5.1
  sentry_dio: ^6.5.1
  sentry_logging: ^6.5.1
  logging: ^1.0.2
  jitsi_meet_wrapper: ^0.0.5
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

dependency_overrides:
  modal_bottom_sheet: ^2.1.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/files/
     - pubspec.yaml
