name: heal_happy
description: Heal happy mobile app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^19.3.48
  url_launcher: ^6.0.12
  dio:
  intl: ^0.17.0
  pubspec_parse: ^1.0.0
  stream_transform: ^2.0.0
  shared_preferences: ^2.0.8
  go_router: ^2.2.1
  heal_happy_sdk:
    path: '../api'
  flutter_riverpod: ^1.0.0-dev.11
  hooks_riverpod: ^1.0.0-dev.11
  flutter_hooks: ^0.18.0
  sentry_flutter: ^6.0.1
  logging: ^1.0.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  sentry_dart_plugin: ^1.0.0-beta.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

sentry:
  project: app
  org: ah-si
  auth_token: 8990b4c7cf704adc8abf3f75044397c612e5fcadc6ad4dc78db7f903b4a3d61f

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - pubspec.yaml

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
