name: heal_happy
description: Heal happy mobile app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.0+35

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  stripe_checkout: ^1.0.0
  file_picker: ^5.2.2
  country_code_picker: ^2.0.2
  collection: ^1.16.0
  syncfusion_flutter_barcodes: ^20.3.57
  syncfusion_flutter_charts: ^20.3.57
  syncfusion_flutter_calendar: ^20.3.57
  url_launcher: ^6.1.6
  dio:
  built_value:
  intl: ^0.17.0
  pubspec_parse: ^1.2.1
  stream_transform: ^2.1.0
  shared_preferences: ^2.0.15
  go_router: ^5.1.9
  heal_happy_sdk:
    path: '../api'
  flutter_riverpod: ^2.1.1
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  sentry_flutter: ^6.15.1
  sentry_dio: ^6.15.1
  sentry_logging: ^6.15.1
  logging: ^1.1.0
  jitsi_meet_wrapper: ^0.0.5
  cupertino_icons: ^1.0.5
  infinite_widgets: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

dependency_overrides:
  modal_bottom_sheet: ^2.1.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/files/
     - pubspec.yaml
