name: heal_happy_sdk
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: '>=4.0.0 <5.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.0 <6.0.0'

dev_dependencies:
  analyzer: ^4.6.0
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
